G_Barber = {
    Price = 50,
    Coords = {
        {x=-814.308,y=-183.823,z=37.568},
        {x=136.826,y=-1708.373,z=29.291},
        {x=-1282.604,y=-1116.757,z=6.990},
        {x=1931.513,y=3729.671,z=32.844},
        {x=1212.840,y=-473.921,z=66.450},
        {x=-32.885,y=-152.319,z=57.076},
        {x=-278.077,y=6228.463,z=31.695},
    },
    Index = {
        HI = 1,
        CHP = {1,1},
        CHS = {1,1},
        BI = 1,
        BOI = 0,
        CBP = {1,1},
        CBS = {1,1},
        EI = 1,
        EOI = 0,
        CEP = {1,1},
        CES = {1,1},
        LI = 1,
        LOI = 0,
        CLP = {1,1},
        CLS = {1,1},
        MI = 1,
        MOI = 0,
        CMP = {1,1},
        CMS = {1,1},
    },
    List = {
        Hair = {
            GetLabelText("CC_M_HS_0"),
            GetLabelText("CC_M_HS_1"), 
            GetLabelText("CC_M_HS_2"), 
            GetLabelText("CC_M_HS_3"), 
            GetLabelText("CC_M_HS_4"),
            GetLabelText("CC_M_HS_5"), 
            GetLabelText("CC_M_HS_6"), 
            GetLabelText("CC_M_HS_7"),
            GetLabelText("CC_M_HS_8"), 
            GetLabelText("CC_M_HS_9"), 
            GetLabelText("CC_M_HS_10"),
            GetLabelText("CC_M_HS_11"), 
            GetLabelText("CC_M_HS_12"), 
            GetLabelText("CC_M_HS_13"),
            GetLabelText("CC_M_HS_14"), 
            GetLabelText("CC_M_HS_15"), 
            GetLabelText("CC_M_HS_16"),
            GetLabelText("CC_M_HS_17"), 
            GetLabelText("CC_M_HS_18"), 
            GetLabelText("CC_M_HS_19"),
            GetLabelText("CC_M_HS_20"), 
            GetLabelText("CC_M_HS_21"), 
            GetLabelText("CC_M_HS_22"),
            GetLabelText("CC_M_HS_23"),
            "Numéro 25",
            "Numéro 26",
            "Numéro 27",
            "Numéro 28",
            "Numéro 29",
            "Numéro 30",
            "Numéro 31",
            "Numéro 32",
            "Numéro 33",
            "Numéro 34",
            "Numéro 35",
            "Numéro 36",
            "Numéro 37",
            "Numéro 38",
            "Numéro 39",
            "Numéro 40",
            "Numéro 41",
            "Numéro 42",
            "Numéro 43",
            "Numéro 44",
            "Numéro 45",
            "Numéro 46",
            "Numéro 47",
            "Numéro 48",
            "Numéro 49",
            "Numéro 50",
            "Numéro 51",
            "Numéro 52",
            "Numéro 53",
            "Numéro 54",
            "Numéro 55",
            "Numéro 56",
            "Numéro 57",
            "Numéro 58",
            "Numéro 59",
            "Numéro 60",
            "Numéro 61",
            "Numéro 62",
            "Numéro 63",
            "Numéro 64",
            "Numéro 65",
            "Numéro 66",
            "Numéro 67",
            "Numéro 68",
            "Numéro 69",
            "Numéro 70",
            "Numéro 71",
            "Numéro 72",
            "Numéro 73",
            "Numéro 74",
            "Numéro 75",
            "Numéro 76",
        },
        Beard = {
            "Barbe de 3 jours",
            "Bouc",
            "Mamène",
            "Bouc Style",
            "Menton",
            "Petite Barbe",
            "Collier",
            "Mal Rasé",
            "D'Artagnan",
            "Moustache",
            "Garnis",
            "Mal Rasée 2",
            "Bouc 2",
            "Collier 2",
            "Collier Prononcé",
            "Collier Tracé",
            "Innovant",
            "Rouflak",
            "Prisonnier",
            "Mexicano",
            "Mexicano Fournis",
            "Mexicano Imposant",
            "Mexicano Tombant",
            "Mexicano Classe",
            "Mexicano Garnis",
            "Biker",
            "Rouflak Chargée",
            "Biker Chargée",
            "Barbu",
        },
        Eyebrows = {
            GetLabelText("CC_EYEBRW_0"),
            GetLabelText("CC_EYEBRW_1"), 
            GetLabelText("CC_EYEBRW_2"), 
            GetLabelText("CC_EYEBRW_3"), 
            GetLabelText("CC_EYEBRW_4"),
            GetLabelText("CC_EYEBRW_5"), 
            GetLabelText("CC_EYEBRW_6"), 
            GetLabelText("CC_EYEBRW_7"),
            GetLabelText("CC_EYEBRW_8"), 
            GetLabelText("CC_EYEBRW_9"), 
            GetLabelText("CC_EYEBRW_10"),
            GetLabelText("CC_EYEBRW_11"), 
            GetLabelText("CC_EYEBRW_12"), 
            GetLabelText("CC_EYEBRW_13"),
            GetLabelText("CC_EYEBRW_14"), 
            GetLabelText("CC_EYEBRW_15"), 
            GetLabelText("CC_EYEBRW_16"),
            GetLabelText("CC_EYEBRW_17"), 
            GetLabelText("CC_EYEBRW_18"), 
            GetLabelText("CC_EYEBRW_19"),
            GetLabelText("CC_EYEBRW_20"), 
            GetLabelText("CC_EYEBRW_21"), 
            GetLabelText("CC_EYEBRW_22"),
            GetLabelText("CC_EYEBRW_23"),
            GetLabelText("CC_EYEBRW_24"),
            GetLabelText("CC_EYEBRW_25"),
            GetLabelText("CC_EYEBRW_26"),
            GetLabelText("CC_EYEBRW_27"),
            GetLabelText("CC_EYEBRW_28"),
            GetLabelText("CC_EYEBRW_29"),
            GetLabelText("CC_EYEBRW_30"),
            GetLabelText("CC_EYEBRW_31"),
            GetLabelText("CC_EYEBRW_32"),
            GetLabelText("CC_EYEBRW_33"),
        },
        Lipstick = {
            GetLabelText("CC_LIPSTICK_0"),
            GetLabelText("CC_LIPSTICK_1"), 
            GetLabelText("CC_LIPSTICK_2"), 
            GetLabelText("CC_LIPSTICK_3"), 
            GetLabelText("CC_LIPSTICK_4"),
            GetLabelText("CC_LIPSTICK_5"), 
            GetLabelText("CC_LIPSTICK_6"), 
            GetLabelText("CC_LIPSTICK_7"),
            GetLabelText("CC_LIPSTICK_8"), 
            GetLabelText("CC_LIPSTICK_9"),
        },
        Makeup = {
            GetLabelText("CC_MKUP_0"),
            GetLabelText("CC_MKUP_1"), 
            GetLabelText("CC_MKUP_2"), 
            GetLabelText("CC_MKUP_3"), 
            GetLabelText("CC_MKUP_4"),
            GetLabelText("CC_MKUP_5"), 
            GetLabelText("CC_MKUP_6"), 
            GetLabelText("CC_MKUP_7"),
            GetLabelText("CC_MKUP_8"), 
            GetLabelText("CC_MKUP_9"), 
            GetLabelText("CC_MKUP_10"),
            GetLabelText("CC_MKUP_11"), 
            GetLabelText("CC_MKUP_12"), 
            GetLabelText("CC_MKUP_13"),
            GetLabelText("CC_MKUP_14"), 
            GetLabelText("CC_MKUP_15"), 
            GetLabelText("CC_MKUP_16"),
            GetLabelText("CC_MKUP_17"), 
            GetLabelText("CC_MKUP_18"), 
            GetLabelText("CC_MKUP_19"),
            GetLabelText("CC_MKUP_20"), 
            GetLabelText("CC_MKUP_21"), 
            GetLabelText("CC_MKUP_22"),
            GetLabelText("CC_MKUP_23"),
            GetLabelText("CC_MKUP_24"),
            GetLabelText("CC_MKUP_25"),
            GetLabelText("CC_MKUP_26"),
            GetLabelText("CC_MKUP_27"),
            GetLabelText("CC_MKUP_28"),
            GetLabelText("CC_MKUP_29"),
            GetLabelText("CC_MKUP_30"),
            GetLabelText("CC_MKUP_31"),
            GetLabelText("CC_MKUP_32"),
            GetLabelText("CC_MKUP_33"),
            GetLabelText("CC_MKUP_34"),
            GetLabelText("CC_MKUP_35"),
            GetLabelText("CC_MKUP_36"),
            GetLabelText("CC_MKUP_37"),
            GetLabelText("CC_MKUP_38"),
            GetLabelText("CC_MKUP_39"),
            GetLabelText("CC_MKUP_40"),
            GetLabelText("CC_MKUP_41"),
            GetLabelText("CC_MKUP_42"),
            GetLabelText("CC_MKUP_43"),
            GetLabelText("CC_MKUP_44"),
            GetLabelText("CC_MKUP_45"),
            GetLabelText("CC_MKUP_46"),
            GetLabelText("CC_MKUP_47"),
            GetLabelText("CC_MKUP_48"),
            GetLabelText("CC_MKUP_49"),
            GetLabelText("CC_MKUP_50"),
            GetLabelText("CC_MKUP_51"),
            GetLabelText("CC_MKUP_52"),
            GetLabelText("CC_MKUP_53"),
            GetLabelText("CC_MKUP_54"),
            GetLabelText("CC_MKUP_55"),
            GetLabelText("CC_MKUP_56"),
            GetLabelText("CC_MKUP_57"),
            GetLabelText("CC_MKUP_58"),
            GetLabelText("CC_MKUP_59"),
            GetLabelText("CC_MKUP_60"),
            GetLabelText("CC_MKUP_61"),
            GetLabelText("CC_MKUP_62"),
            GetLabelText("CC_MKUP_63"),
            GetLabelText("CC_MKUP_64"),
            GetLabelText("CC_MKUP_65"),
            GetLabelText("CC_MKUP_66"),
            GetLabelText("CC_MKUP_67"),
            GetLabelText("CC_MKUP_68"),
            GetLabelText("CC_MKUP_69"),
            GetLabelText("CC_MKUP_70"),
            GetLabelText("CC_MKUP_71"),
            GetLabelText("CC_MKUP_72"),
            GetLabelText("CC_MKUP_73"),
            GetLabelText("CC_MKUP_74"),
            GetLabelText("CC_MKUP_75"),
            GetLabelText("CC_MKUP_76"),
            GetLabelText("CC_MKUP_77"),
            GetLabelText("CC_MKUP_78"),
            GetLabelText("CC_MKUP_79"),
            GetLabelText("CC_MKUP_80"),
        },
    }
}